import { resources } from '../data/resources'
import { recipes } from '../data/recipes'
import { processes } from '../data/processes'
import type { GameState, OptimizationReport, ProcessDefinition, ProcessInstance, ResourceId } from './types'
const clamp=(n:number,min=0,max=1)=>Math.max(min,Math.min(max,n))
export function computeWorkerFactor(workers:number,maxWorkers:number){ return maxWorkers===0 ? 1 : clamp(workers/maxWorkers) }
export function computeLogisticsFactor(process: ProcessInstance | ProcessDefinition, base=1){ return clamp(base - ('logisticsSensitivity' in process ? process.logisticsSensitivity : processes[process.type].logisticsSensitivity) * (1-base), .15, 1.2) }
export function computeTechMultiplier(state:GameState){ let m=1; if(state.researched.includes('efficient_connections')) m+=.04; if(state.researched.includes('compacted_paths')) m+=.04; return m }
export function computeInputAvailabilityFactor(state:GameState, recipeId?:string, throughput=1){ if(!recipeId) return 1; const recipe=recipes[recipeId]; let factor=1; for(const [r,amount] of Object.entries(recipe.inputs) as [ResourceId,number][]) { const need=(amount*60/recipe.cycleSeconds)*throughput; if(need>0) factor=Math.min(factor, clamp(state.resources[r].amount/(need/3))) } return factor }
export function computeStorageFactor(state:GameState, recipeId?:string){ if(!recipeId) return 1; const recipe=recipes[recipeId]; let factor=1; for(const [r,amount] of Object.entries(recipe.outputs) as [ResourceId,number][]) { if(amount>0) { const res=state.resources[r]; factor=Math.min(factor, res.capacity<=0?1:clamp((res.capacity-res.amount)/(res.capacity*.08))) } } return factor }
export function computeEffectiveProduction(base:number, worker:number, logistics:number, tech:number, input:number, storage:number){ return base*worker*logistics*tech*input*storage }
export function computeNetProduction(produced:Partial<Record<ResourceId,number>>, consumed:Partial<Record<ResourceId,number>>){ const net:Partial<Record<ResourceId,number>>={}; for(const id of Object.keys(resources) as ResourceId[]) net[id]=(produced[id]??0)-(consumed[id]??0); return net }
export function computeBottlenecks(state:GameState, net:Partial<Record<ResourceId,number>>){ return (Object.keys(state.resources) as ResourceId[]).filter(r=>state.resources[r].visible && ((net[r]??0)<0 || state.resources[r].amount<state.resources[r].capacity*.08)) }
export function estimateTimeToAfford(state:GameState, cost:Partial<Record<ResourceId,number>>, net:Partial<Record<ResourceId,number>>){ let max=0; for(const [r,v] of Object.entries(cost) as [ResourceId,number][]) { const missing=Math.max(0,v-state.resources[r].amount); if(missing===0) continue; const rate=net[r]??0; if(rate<=0) return Infinity; max=Math.max(max, missing/rate*60) } return max }
export function computeResilienceScore(state:GameState){ const stock=state.resources.resilience.amount/Math.max(1,state.resources.resilience.capacity); const tech=['strategic_reserves','preventive_maintenance','process_redundancy','disturbance_mitigation'].filter(t=>state.researched.includes(t as never)).length*.12; return clamp(stock*.7+tech) }
export function computePerturbationRisk(state:GameState, intensity=40){ return clamp((intensity/100) - computeResilienceScore(state)*.55) }
export function computeOptimizationScore(state:GameState): OptimizationReport { const active=state.processes.filter(p=>!p.paused && p.status==='Funcionando').length; const productive=state.processes.filter(p=>processes[p.type].recipeId && processes[p.type].maxWorkers>0).length || 1; const processEfficiency=state.processes.reduce((s,p)=>s+p.efficiency,0)/Math.max(1,state.processes.length); const logisticsEfficiency=state.processes.reduce((s,p)=>s+p.logisticsEfficiency,0)/Math.max(1,state.processes.length); const assigned=state.processes.reduce((s,p)=>s+p.workers,0); const pop=Math.max(1,Math.floor(state.resources.population.amount)); const workerUtilization=clamp(assigned/pop); const visible=(Object.keys(state.resources) as ResourceId[]).filter(r=>state.resources[r].visible && resources[r].storage); const resourceStability=visible.reduce((s,r)=>{ const res=state.resources[r]; const net=res.producedPerMinute-res.consumedPerMinute; return s+clamp(res.amount/Math.max(1,res.capacity))*(net<0?.65:1) },0)/Math.max(1,visible.length); const resilienceScore=computeResilienceScore(state); const activeProcessRatio=active/productive; const stopped=state.processes.filter(p=>['Falta input','Sin trabajadores','Output lleno','Baja eficiencia logística'].includes(p.status)).length; const limitingResource=visible.find(r=>state.resources[r].amount<state.resources[r].capacity*.08 || state.resources[r].producedPerMinute-state.resources[r].consumedPerMinute<0); const bottlenecks=state.connections.filter(c=>c.active&&c.efficiency<.55).map(c=>`${processes[c.from].name} → ${processes[c.to].name}`); const penalties=clamp(stopped*.035 + bottlenecks.length*.025 + (limitingResource?.length? .05:0),0,.35); const raw=.25*processEfficiency+.20*logisticsEfficiency+.20*workerUtilization+.15*resourceStability+.10*resilienceScore+.10*activeProcessRatio-penalties; const optimizationScore=Math.round(clamp(raw,0,1)*100); const previous=state.history.at(-6)?.optimizationScore ?? optimizationScore; const mainLoss=stopped?`${processes[state.processes.find(p=>p.status!=='Funcionando' && processes[p.type].recipeId)?.type ?? 'townCenter'].name} parado o limitado`: bottlenecks[0] ? `Flujo limitado: ${bottlenecks[0]}` : limitingResource ? `Recurso limitante: ${resources[limitingResource].name}` : 'Sistema estable; busca una meta de eficiencia más alta'; return {optimizationScore,trend:optimizationScore-previous,processEfficiency,logisticsEfficiency,workerUtilization,resourceStability,resilienceScore,activeProcessRatio,limitingResource,mainLoss,penalties,bottlenecks} }
export const logisticEfficiency=(connected:boolean, roadTech:boolean)=>connected?(roadTech?1:.9):.45
export const recipeThroughput=(process:ProcessInstance)=>process.workers>0?process.workers*process.efficiency:process.efficiency
export const defensePower=(state:GameState)=>state.resources.resilience.amount
